# Generated by Django 5.0.6 on 2024-06-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Required", max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        help_text="Required", max_length=100, verbose_name="Dose"
                    ),
                ),
                (
                    "presentation",
                    models.TextField(help_text="Required", verbose_name="Presentation"),
                ),
                (
                    "unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Required",
                        max_digits=5,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Required", max_length=100, verbose_name="Country"
                    ),
                ),
            ],
        ),
    ]
